##########################################################
##
## 端口，app名字等应用基础配置
##
##########################################################
server:
  port: 8080

spring:
  application:
    name: time

  ##########################################################
  ##
  ## 微服务配置
  ##
  ##########################################################
  cloud:
    nacos:
      discovery:
        ip: localhost:8848