##########################################################
##
## 端口，app名字等应用基础配置
##
##########################################################
server:
  port: 8080

spring:
  application:
    name: time

  ##########################################################
  ##
  ## 微服务配置
  ##
  ##########################################################
  cloud:
    nacos:
      discovery:
        server-addr: 10.20.0.1:8848

##########################################################
##
## 服务地址配置
##
##########################################################
service-url:
  order-service: http://order
  time-service: http://time
  goods-service: http://gooods
  stock-service: http://stock